title: 'ok'
sections:
  - title: 'Basic'
    files: 'viz/specs/basic'
  - title: 'Background'
    files: 'viz/specs/background'
  - title: 'GoToSectionScene'
    files: 'viz/specs/goToSceneSection'
  - title: 'Visual'
    files: 'viz/specs/visual'
  - title: 'Character'
    files: 'viz/specs/character'
  - title: 'Dialogue'
    files: 'viz/specs/dialogue'
  - title: 'Choice'
    files: 'viz/specs/choice'
  - title: 'Animation'
    files: 'viz/specs/animation'
  - title: 'Complete'
    files: 'viz/specs/complete'